# Generated by Django 5.2.5 on 2025-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_international',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_nationwide',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suit_type',
        ),
        migrations.AddField(
            model_name='product',
            name='piece_type',
            field=models.CharField(choices=[('2-piece', '2 Piece'), ('3-piece', '3 Piece')], default='3-piece', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stitched', 'Stitched'), ('unstitched', 'Unstitched')], default='unstitched', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes e.g. S,M,L', max_length=100),
        ),
    ]
