# Generated by Django 5.2.5 on 2025-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_about_product_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_product',
            field=models.TextField(blank=True, help_text="Detailed description for 'About the Product'"),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_international',
            field=models.CharField(default='5-7 working days international', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_nationwide',
            field=models.CharField(default='2-3 working days nationwide', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Disclaimer for product'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, help_text='e.g. Lawn, Cotton, Silk', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique SKU', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes e.g. S,M,L,XL', max_length=100),
        ),
    ]
