# Generated by Django 5.2.5 on 2025-10-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_image_product_image1_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stores the discount percentage (auto-calculated)', max_digits=5, null=True),
        ),
    ]
