# Generated by Django 5.2.5 on 2025-10-17 11:15

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.png', upload_to=store.models.upload_to),
        ),
    ]
